version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "frehner@users.noreply.github.com"
            git config --global user.name "CircleCI on behalf of Anthony Frehner"
            echo "machine github.com login frehner password $GITHUB_TOKEN" > ~/.netrc
            cd website
            yarn install --frozen-lockfile
            GIT_USER=frehner yarn deploy
  build-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Building
          command: |
            cd website 
            yarn install --frozen-lockfile
            yarn build
      - run:
          name: Ping FeaturePeek
          command: bash <(curl -s https://peek.run/ci)
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: master
  build:
    jobs:
      - build-website:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy-website:
          filters:
            branches:
              only:
                - master
